app/models/PostModel.py
from dataclasses import dataclass
from datetime import date


@dataclass
class Post:
    id: int = None
    author_id: int = None
    created: date = None
    title: str = None
    body: str = None

app/models/UserModel.py
from dataclasses import dataclass


@dataclass
class User:
    id: int = None
    username: str = None
    passwd: str = None

app/__init__.py
import os
from flask import Flask


def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY="dev",
        DATABASE=os.path.join(app.instance_path, "flaskr.sqlite"),
    )
    import logging

    logging.basicConfig(
        filename="logs/app.log",
        level=logging.INFO,
        format="%(asctime)s - %(levelname)s - %(name)s - %(message)s",
    )

    from . import db

    db.init_app(app)

    from app.views import AuthView
    from app.views import PostView

    app.register_blueprint(AuthView.bp)
    app.register_blueprint(PostView.bp)
    app.add_url_rule("/", endpoint="index")

    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile("config.py", silent=True)
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    return app

app/views/AuthView.py
import functools

from flask import (
    Blueprint,
    flash,
    g,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from werkzeug.security import check_password_hash, generate_password_hash

from app.models.UserModel import User
from app.repositories.impl.UserRepositoryImpl import new_user_repo

import logging

bp = Blueprint("auth", __name__, url_prefix="/auth")
user_repo = new_user_repo()


@bp.route("/register", methods=("GET", "POST"))
def register():
    logging.info("registering")
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]

        error = None

        if not username:
            error = "Username is required."
        elif not password:
            error = "Password is required."

        user = User()
        user.username = username
        user.passwd = password
        logging.info(f"new user: {user}")

        if error is None:
            try:
                user_repo.new(user)
            except Exception as e:
                logging.error(f"Error creating user\n{e}")
                error = f"User {username} is already registered."
            else:
                return redirect(url_for("auth.login"))

        flash(error)

    return render_template("auth/register.html")


@bp.route("/login", methods=("GET", "POST"))
def login():
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]
        error = None
        logging.info(f"form login: {username} {password}")
        user = user_repo.get_by_username(username)
        logging.info(f"user check: {user}")
        if user is None:
            error = "Incorrect username."
        elif not check_password_hash(user.passwd, password):
            error = "Incorrect password."

        if error is None:
            session.clear()
            session["user_id"] = user.id
            return redirect(url_for("index"))

        flash(error)

    return render_template("auth/login.html")


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get("user_id")

    if user_id is None:
        g.user = None
    else:
        g.user = user_repo.get_by_id(user_id)


@bp.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("index"))


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for("auth.login"))

        return view(**kwargs)

    return wrapped_view

app/views/PostView.py
from flask import Blueprint, flash, g, redirect, render_template, request, url_for
from werkzeug.exceptions import abort
from app.models.PostModel import Post

from app.views.AuthView import login_required
from app.repositories.impl.PostRepositoryImpl import new_post_repo

bp = Blueprint("blog", __name__)
post_repository = new_post_repo()


@bp.route("/")
def index():
    posts = post_repository.get_all()
    return render_template("blog/index.html", posts=posts)


@bp.route("/create", methods=("GET", "POST"))
@login_required
def create():
    if request.method == "POST":
        title = request.form["title"]
        body = request.form["body"]
        error = None

        if not title:
            error = "Title is required."

        if error is not None:
            flash(error)
        else:
            post = Post()
            post.title = title
            post.body = body
            post.author_id = g.user["id"]

            post_repository.new(post)
            return redirect(url_for("blog.index"))

    return render_template("blog/create.html")


def get_post(id, check_author=True):
    post = post_repository.get_by_id(id)

    if post is None or post == []:
        abort(404, f"Post id {id} doesn't exist.")

    if check_author and post.author_id != g.user["id"]:
        abort(403)

    return post


@bp.route("/<int:id>/update", methods=("GET", "POST"))
@login_required
def update(id):
    post = get_post(id)

    if request.method == "POST":
        title = request.form["title"]
        body = request.form["body"]
        error = None

        if not title:
            error = "Title is required."

    return render_template("blog/update.html", post=post)


@bp.route("/<int:id>/delete", methods=("POST",))
@login_required
def delete(id):
    post = get_post(id)
    return redirect(url_for("blog.index"))

app/templates/base.html
<!doctype html>
<title>{% block title %}{% endblock %} - Flaskr</title>
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
<script src="{{ url_for('static', filename='js/htmx.min.js') }}"></script>
<script src="https://unpkg.com/htmx.org/dist/ext/response-targets.js"></script>
<script src="https://unpkg.com/htmx.org/dist/ext/debug.js"></script>
<link rel="icon" href="{{ url_for('static', filename='img/daft.jpg')}}" type="image/x-icon">
<nav>
  <h1>Flaskr</h1>
  <ul>
    {% if g.user %}
      <li><span>{{ g.user['username'] }}</span>
      <li><a hx-get="{{ url_for('auth.logout') }}" hx-target=".content">Log Out</a>
    {% else %}
      <li><a hx-get="{{ url_for('auth.register') }}" hx-target=".content">Register</a>
      <li><a hx-get="{{ url_for('auth.login') }}" hx-target=".content">Log In</a>
    {% endif %}
  </ul>
</nav>
<section class="content">
  {% include 'auth/login.html' %}
</section>

app/templates/blog/create.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}New Post{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="title">Title</label>
    <input name="title" id="title" value="{{ request.form['title'] }}" required>
    <label for="body">Body</label>
    <textarea name="body" id="body">{{ request.form['body'] }}</textarea>
    <input type="submit" value="Save">
  </form>
{% endblock %}

app/templates/blog/index.html
{% extends 'base.html' %}

<header>
  <h1>Posts</h1>
  {% if g.user %}
    <a class="action" href="{{ url_for('blog.create') }}">New</a>
  {% endif %}
</header>

{% block content %}
  {% for post in posts %}
    <article class="post">
      <header>
        <div>
          <h1>{{ post['title'] }}</h1>
          <div class="about">by {{ post['username'] }} on {{ post['created'].strftime('%Y-%m-%d') }}</div>
        </div>
        {% if g.user['id'] == post['author_id'] %}
          <a class="action" href="{{ url_for('blog.update', id=post['id']) }}">Edit</a>
        {% endif %}
      </header>
      <p class="body">{{ post['body'] }}</p>
    </article>
    {% if not loop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endblock %}

app/templates/blog/update.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Edit "{{ post['title'] }}"{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="title">Title</label>
    <input name="title" id="title"
      value="{{ request.form['title'] or post['title'] }}" required>
    <label for="body">Body</label>
    <textarea name="body" id="body">{{ request.form['body'] or post['body'] }}</textarea>
    <input type="submit" value="Save">
  </form>
  <hr>
  <form action="{{ url_for('blog.delete', id=post['id']) }}" method="post">
    <input class="danger" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
  </form>
{% endblock %}